version: '3.8'

services:
  # 1. Dịch vụ Laravel Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mynotes-app
    container_name: mynotes-app-container
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    volumes:
      - ./:/var/www
    networks:
      - mynotes-network

  # 2. Dịch vụ Nginx Web Server (Cổng 80)
  web:
    image: nginx:alpine
    container_name: mynotes-nginx-container
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - mynotes-network
    depends_on:
      - app

  # 3. Dịch vụ Node.js WebSocket Server (Cổng 8080 - Khớp với báo cáo) 🌟
  websocket:
    image: node:18-alpine
    container_name: mynotes-websocket-container
    restart: unless-stopped
    working_dir: /var/www
    ports:
      - "8080:8080"
    volumes:
      - ./:/var/www
    # Lệnh khởi chạy ngầm file server websocket của Dev B
    command: node websocket-server.js
    networks:
      - mynotes-network

networks:
  mynotes-network:
    driver: bridge
