version: '3.8'

services:
  # 1. Ứng dụng Laravel Backend
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: final-note-app
    container_name: note-laravel-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
    volumes:
      - .:/var/www
    networks:
      - note-network

  # 2. Web Server Nginx
  webserver:
    image: nginx:alpine
    container_name: note-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - note-network
    depends_on:
      - app

  # 3. Realtime WebSocket Server (Node.js)
  websocket:
    image: node:20-alpine
    container_name: note-websocket
    restart: unless-stopped
    working_dir: /usr/src/app
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    command: node websocket-server.js
    networks:
      - note-network

networks:
  note-network:
    driver: bridge
